#ban ip
server {
listen 80 default_server;
listen [::]:80 default_server;
rewrite ^ http://simonsmh.tk$request_uri?;
}

#defalt
server {
listen 80;
listen [::]:80;
server_name simonsmh.tk www.simonsmh.tk;
root /var/www/simonsmh.tk; 
index index.php index.html index.htm;
location /generate_204 { return 204;
}
location ~ \.php$ {
fastcgi_split_path_info ^(.+\.php)(/.+)$;
fastcgi_pass unix:/var/run/php5-fpm.sock;
fastcgi_index index.php;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;	
}
}

#blog.simonsmh.tk
server {
listen 80;
listen [::]:80;
root /var/www/blog.simonsmh.tk;
index index.php index.html index.htm;
server_name blog.simonsmh.tk www.blog.simonsmh.tk;
location / {
include wordpress.conf;
}
location ~ \.php$ {
fastcgi_split_path_info ^(.+\.php)(/.+)$;
fastcgi_pass unix:/var/run/php5-fpm.sock;
fastcgi_index index.php;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
}

#tieba
server {
listen 80;
listen [::]:80;
root /var/www/tieba.simonsmh.tk;
index index.php index.html index.htm;
server_name tieba.simonsmh.tk www.tieba.simonsmh.tk;
location / {
include wordpress.conf;
}
location ~ \.php$ {
fastcgi_split_path_info ^(.+\.php)(/.+)$;
fastcgi_pass unix:/var/run/php5-fpm.sock;
fastcgi_index index.php;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
}
