#One line add to nginx.conf
#include /var/www/simonsmh.tk/nginxproxy/*;
#guide domain which is on 80 port
server { 
listen 80 default_server;
listen [::]:80 default_server;
rewrite ^ $scheme://simonsmh.tk/;
#Fonts cache
location ~* ^.+\.(eot|ttf|otf|woff|svg|woff2)$ {
access_log off;
expires max;
}
}
#enable ssl in all secon domain server
#./letsencrypt-auto certonly --standalone --email simonsmh@gmail.com -d simonsmh.tk -d blog.simonsmh.tk -d tieba.simonsmh.tk -d openwrt.simonsmh.tk -d bt.simonsmh.tk -d pan.simonsmh.tk -d ipv6.simonsmh.tk -d ports.simonsmh.tk -d home.simonsmh.tk
#expire on 2016-08-07
#add "--server https://acme-staging.api.letsencrypt.org/directory" to avoid rate limit problem.
server {
listen 80;
listen [::]:80;
server_name simonsmh.tk;
rewrite ^(.*) https://$server_name$request_uri permanent;
}
server {
listen 80;
listen [::]:80;
server_name ipv6.simonsmh.tk;
rewrite ^(.*) https://$server_name$request_uri permanent;
}
server {
listen 80;
listen [::]:80;
server_name blog.simonsmh.tk;
rewrite ^(.*) https://$server_name$request_uri permanent;
}
server {
listen 80;
listen [::]:80;
server_name tieba.simonsmh.tk;
rewrite ^(.*) https://$server_name$request_uri permanent;
}
server {
listen 80;
listen [::]:80;
server_name bt.simonsmh.tk;
rewrite ^(.*) https://$server_name$request_uri permanent;
}
server {
listen 80;
listen [::]:80;
server_name pan.simonsmh.tk;
rewrite ^(.*) https://$server_name$request_uri permanent;
}
#defalt
server {
listen 443 http2 ssl;
listen [::]:443 http2 ssl;
server_name simonsmh.tk ipv6.simonsmh.tk www.simonsmh.tk;
root /var/www/simonsmh.tk; 
index index.php index.html index.htm;
#redir to file dir, not using link
location ~ /(files|sfiles)/ {
root /var/wwwfiles/; 
}
#Disable upload&run .php files
location ~ ^/(files|sfiles)/.*\.php(\/.*)*$
{
deny all; 
}
#Fix Access-Control-Allow-Origin for glype
location / {
add_header Access-Control-Allow-Origin *;
}
location ~ .*\.php(\/.*)*$ {
set $path_info "";
fastcgi_split_path_info ^(.+\.php)(/.+)$;
fastcgi_pass unix:/run/php/php7.0-fpm.sock;
fastcgi_index index.php;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param SCRIPT_NAME $fastcgi_script_name;
fastcgi_param PATH_INFO $path_info;
}
error_page  310 /310.php;
error_page  401 /401.php;
error_page  403 /403.php;
error_page  404 /404.php;
error_page  502 /502.php;
}

#blog.simonsmh.tk
server {
listen 443 http2 ssl;
listen [::]:443 http2 ssl;
root /var/www/blog.simonsmh.tk;
index index.php index.html index.htm;
server_name blog.simonsmh.tk;
if (!-e $request_filename) {
rewrite ^(.*)$ /index.php$1 last;
}
location ~ .*\.php(\/.*)*$ {
set $path_info "";
fastcgi_split_path_info ^(.+\.php)(/.+)$;
fastcgi_pass unix:/run/php/php7.0-fpm.sock;
fastcgi_index index.php;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param SCRIPT_NAME $fastcgi_script_name;
fastcgi_param PATH_INFO $path_info;
}
}

#tieba
server {
listen 443 http2 ssl;
listen [::]:443 http2 ssl;
root /var/www/tieba.simonsmh.tk;
index index.php index.html index.htm;
server_name tieba.simonsmh.tk;
location ~ .*\.php(\/.*)*$ {
set $path_info "";
fastcgi_split_path_info ^(.+\.php)(/.+)$;
fastcgi_pass unix:/run/php/php7.0-fpm.sock;
fastcgi_index index.php;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param SCRIPT_NAME $fastcgi_script_name;
fastcgi_param PATH_INFO $path_info;
}
}

#transmission
server {
listen 443 http2 ssl;
listen [::]:443 http2 ssl;
server_name bt.simonsmh.tk;
location /{
proxy_pass http://127.0.0.1:9091;
proxy_set_header Accept-Encoding "";
}
error_page  310 https://simonsmh.tk/310.php;
error_page  401 https://simonsmh.tk/401.php;
error_page  403 https://simonsmh.tk/403.php;
error_page  404 https://simonsmh.tk/404.php;
error_page  502 https://simonsmh.tk/502.php;
}

#seafiles
server {
listen 443 http2 ssl;
listen [::]:443 http2 ssl;
server_name pan.simonsmh.tk;
location /{
proxy_pass http://127.0.0.1:8000;
proxy_set_header Accept-Encoding "";
}
error_page  310 https://simonsmh.tk/310.php;
error_page  401 https://simonsmh.tk/401.php;
error_page  403 https://simonsmh.tk/403.php;
error_page  404 https://simonsmh.tk/404.php;
error_page  502 https://simonsmh.tk/502.php;
}

#openwrt
server {
listen 80;
listen [::]:80;
server_name openwrt.simonsmh.tk;
location /{
proxy_redirect http://downloads.openwrt.org/ /;
proxy_pass http://downloads.openwrt.org;
proxy_set_header Accept-Encoding "";
subs_filter downloads.openwrt.org openwrt.simonsmh.tk;
}
}
server {
listen 443 http2 ssl;
listen [::]:443 http2 ssl;
server_name openwrt.simonsmh.tk;
location /{
proxy_redirect https://downloads.openwrt.org/ /;
proxy_pass https://downloads.openwrt.org;
proxy_set_header Accept-Encoding "";
subs_filter downloads.openwrt.org openwrt.simonsmh.tk;
}
}
server {
listen 80;
listen [::]:80;
server_name ports.simonsmh.tk;
location /{
proxy_redirect http://ports.ubuntu.com/ /;
proxy_pass http://ports.ubuntu.com;
proxy_set_header Accept-Encoding "";
subs_filter ports.ubuntu.com ports.simonsmh.tk;
}
}

#ubuntu
server {
listen 443 http2 ssl;
listen [::]:443 http2 ssl;
server_name ports.simonsmh.tk;
location /{
proxy_redirect https://ports.ubuntu.com/ /;
proxy_pass https://ports.ubuntu.com;
proxy_set_header Accept-Encoding "";
subs_filter ports.ubuntu.com ports.simonsmh.tk;
}
}
#wikipedia welcome page
server {
listen 80;
listen [::]:80;
server_name wiki.simonsmh.tk www.wiki.simonsmh.tk;
location /{
proxy_redirect https://www.wikipedia.org/ /;
proxy_redirect http://www.wikipedia.org/ /;
proxy_pass https://www.wikipedia.org;
proxy_set_header Accept-Encoding "";
subs_filter https:// http:// r;
subs_filter www.wikipedia.org wiki.simonsmh.tk r;
#fit below supported languages
subs_filter zh.wikipedia.org zh.wiki.simonsmh.tk r;
subs_filter zh.m.wikipedia.org zh.m.wiki.simonsmh.tk r;
subs_filter en.wikipedia.org en.wiki.simonsmh.tk r;
subs_filter en.m.wikipedia.org en.m.wiki.simonsmh.tk r;
subs_filter ja.wikipedia.org ja.wiki.simonsmh.tk r;
subs_filter ja.m.wikipedia.org ja.m.wiki.simonsmh.tk r;
}
}

#wiki-chinese and wikim-chinese
server {
listen 80;
listen [::]:80;
server_name zh.wiki.simonsmh.tk;
location /{
proxy_redirect https://zh.wikipedia.org/ /;
proxy_redirect http://zh.wikipedia.org/ /;
proxy_pass https://zh.wikipedia.org;
proxy_set_header Accept-Encoding "";
subs_filter https:// http:// r;
subs_filter zh.wikipedia.org zh.wiki.simonsmh.tk r;
subs_filter zh.m.wikipedia.org zh.m.wiki.simonsmh.tk r;
}
}
server {
listen 80;
listen [::]:80;
server_name zh.m.wiki.simonsmh.tk;
location /{
proxy_redirect https://zh.m.wikipedia.org/ /;
proxy_redirect http://zh.m.wikipedia.org/ /;
proxy_pass https://zh.m.wikipedia.org;
proxy_set_header Accept-Encoding "";
subs_filter https:// http:// r;
subs_filter zh.wikipedia.org zh.wiki.simonsmh.tk r;
subs_filter zh.m.wikipedia.org zh.m.wiki.simonsmh.tk r;
}
}

#wiki-other language
#wiki-english and wikim-english
server {
listen 80;
listen [::]:80;
server_name en.wiki.simonsmh.tk;
location /{
proxy_redirect https://en.wikipedia.org/ /;
proxy_redirect http://en.wikipedia.org/ /;
proxy_pass https://en.wikipedia.org;
proxy_set_header Accept-Encoding "";
subs_filter https:// http:// r;
subs_filter en.wikipedia.org en.wiki.simonsmh.tk r;
subs_filter en.m.wikipedia.org en.m.wiki.simonsmh.tk r;
}
}
server {
listen 80;
listen [::]:80;
server_name en.m.wiki.simonsmh.tk;
location /{
proxy_redirect https://en.m.wikipedia.org/ /;
proxy_redirect http://en.m.wikipedia.org/ /;
proxy_pass https://en.m.wikipedia.org;
proxy_set_header Accept-Encoding "";
subs_filter https:// http:// r;
subs_filter en.wikipedia.org en.wiki.simonsmh.tk r;
subs_filter en.m.wikipedia.org en.m.wiki.simonsmh.tk r;
}
}

#wiki-japan and wikim-japan
server {
listen 80;
listen [::]:80;
server_name ja.wiki.simonsmh.tk;
location /{
proxy_redirect https://ja.wikipedia.org/ /;
proxy_redirect http://ja.wikipedia.org/ /;
proxy_pass https://ja.wikipedia.org;
proxy_set_header Accept-Encoding "";
subs_filter https:// http:// r;
subs_filter ja.wikipedia.org ja.wiki.simonsmh.tk r;
subs_filter ja.m.wikipedia.org ja.m.wiki.simonsmh.tk r;
}
}
server {
listen 80;
listen [::]:80;
server_name ja.m.wiki.simonsmh.tk;
location /{
proxy_redirect https://ja.m.wikipedia.org/ /;
proxy_redirect http://ja.m.wikipedia.org/ /;
proxy_pass https://ja.m.wikipedia.org;
proxy_set_header Accept-Encoding "";
subs_filter https:// http:// r;
subs_filter ja.wikipedia.org ja.wiki.simonsmh.tk r;
subs_filter ja.m.wikipedia.org ja.m.wiki.simonsmh.tk r;
}
}

#fatesakura
server {
listen 80;
listen [::]:80;
root /var/www/fatesakura.tk;
index index.php index.html index.htm;
server_name fatesakura.tk;
location / {
if (-d $request_filename){
rewrite ^/(.*)([^/])$ /$1$2/ permanent;
}
if (-f $request_filename/index.html){
rewrite (.*) $1/index.html break;
}
if (-f $request_filename/index.php){
rewrite (.*) $1/index.php;
}
if (!-f $request_filename){
rewrite (.*) /index.php;
}
}
location ~ \.php$ {
fastcgi_split_path_info ^(.+\.php)(/.+)$;
fastcgi_pass unix:/run/php/php7.0-fpm.sock;
fastcgi_index index.php;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
}
